---
title: "Saldo de Exportações por Estado"
resource_files:
- data_bi/capitais_lat_lon.csv
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(sf)
library(networkD3)
library(igraph)
library(tidygraph)




capitais <- read_csv("data_bi/capitais_lat_lon.csv")
df_to_from <- read_rds("data_bi/df_to_from.rds") %>%
  left_join(capitais, by=c("from"="estado")) 

states <- read_rds("data_bi/poligonos_estados.rds")

regioes <- c(`Centro Oeste` = "CO",
              Nordeste = "NE",
              Norte = "N",
              Sudeste = "SE",
              Sul = "S")
estados <- c(capitais$estado)



```




# Mapa

## Column {.sidebar column-width=100}

```{r}
radioButtons("ano", "Ano", c("2017","2018"), selected="2017")
#selectInput("regiao", "Região", choices=regioes, selected = "SE")
selectInput("estados", "Estados", choices=estados, selected = c("SP"))
```



## Row {row-height = 400}


### 

```{r}


renderPlot({
  df_map <- df_to_from %>%
    filter(ano==input$ano) %>%
    left_join(capitais%>%select(-regiao) %>% rename(xend=lon, yend=lat), by=c(to="estado"))
  
  states %>%
    ggplot() +
    geom_sf( fill="#2D3E50", color="#FEBF57", size=.15, show.legend = FALSE) +
    geom_point(data=df_map, aes(x=lon, y=lat, size=weight), color="orange") +
    geom_curve(data=df_map%>%filter(from == input$estados),
               aes(x = lon, y = lat, xend = xend, yend = yend, # draw edges as arcs
                   size = weight), color="green",
               curvature = 0.1, alpha = 0.5,
               arrow=arrow(length=unit(0.05, units="npc"))) +
    theme_minimal() +
    theme(legend.position="none")
})





```


# D3 Network

```{r}




df_from_to_2017 <- df_to_from %>% filter(ano=="2017") %>%
  filter(weight>500) %>%
  select(-ano, -lat, -lon, -regiao)


net_centrality <- as_tbl_graph(df_from_to_2017, directed=T) %>%
    mutate(centrality = centrality_betweenness()) %>% 
  as_tibble()


nodes_capitais <- capitais  %>%
  mutate(id=sprintf("s%.2d",(1:(nrow(.))))) %>% 
  select(id, estado, regiao)

df_d3 <- df_from_to_2017  %>%
  #filter(weight>500) %>%
  left_join(nodes_capitais%>%rename(id_from=id),by=c(from = "estado")) %>%
  left_join(nodes_capitais %>% rename(id_to=id), by=c(to = "estado"))  %>%
  select(id_from, id_to, everything())


links_d3 <- tibble(from=as.integer(factor(df_d3$id_from))-1L,
                       to=as.integer(factor(df_d3$id_to))-1L,
                   weight=df_d3$weight/1000) 
nodes_d3 <- nodes_capitais %>%
  left_join(net_centrality, by=c(estado="name")) %>%
  mutate(idn=factor(nodes_capitais$estado, levels=nodes_capitais$estado)) %>%
  select(idn, id, everything()) 


forceNetwork(Links = links_d3, Nodes = nodes_d3, Source="from", Target="to",
             NodeID = "idn", # must be first column in Nodes df
             Group = "regiao", opacity=1, zoom=T, legend=T, charge=-1500,
             Nodesize="centrality", Value="weight", fontSize=20)


```
